[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "JDXp7QVMLbFR6QKmx8Zwhef6cqMw3nWwmrVqx8K5yB7A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/kartik/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
